---
# basePath is used if the site is hosted in a subfolder
basePath: #/p5-daphp-oc

#siteURL is the domain name where the site is hosteds
siteURL: #http://localhost

# mailer is the credentials to smtp serve use to send mails
mailer:
  smtpServerAdresse: #smtp.exemple.com
  smtpServerPort: #587
  mailAdresse: #user@domain.ext
  mailPassword: #azerty

# dataBase is the credentials to connect to dababase
dataBase:
  hostName: #localhost
  dbName: #frameworkOCauth
  login: #root
  password: #root
...